# app_id: F900F6A6-418E-4D13-87BF-0CAE40C93559
# publisher: My Company, Inc.
# publisher_url: https://www.example.com/
# display_name: Update_test
# create_desktop_icon: false
# install_dir_name: Update_test
# locales:
#   - kr

script_template: "./inno_setup.iss"